### PR TITLE
feat: supporting whpu login process

### PR DESCRIPTION
**Pull request by beetcb**
> still need help to test: I'm not quite familiar with java. I hope you could take the time to test it. (BTW: thank you for this awesome `api` ✨)
- `here is the login url`: [url](http://cas.whpu.edu.cn/authserver/login?service=http%3A%2F%2Fehall.whpu.edu.cn%2Flogin%3Fservice%3Dhttp%3A%2F%2Fehall.whpu.edu.cn%2Fywtb-portal%2FLite%2Findex.html%23%2Fhome%2FLite_home) 
- `college`: `whpu`
- `ehall`: [url](http://ehall.whpu.edu.cn/new/portal/browerTips.html)

### CODE REVIEW

**Comment by ZimoLoveShuang** [comment]
I try to merge. but unfortunately, something was wrong. maybe you should give me a account and password to test, thank you

**Comment by beetcb** [comment]
I sent it to your qq email address.

**Comment by ZimoLoveShuang** [comment]
> I sent it to your qq email address.

fine

**Comment by ZimoLoveShuang** [comment]
now, finished, maybe you can try this api for login. enjoy it!

**Comment by beetcb** [comment]
thank you again. great work🎉

**Pull request merged**
